//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IPO_JDE_conn.WebReference2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service2Soap", Namespace="http://tempuri.org/")]
    public partial class Service2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GAL_Pobierz_zdjeciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GAL_dane_zleceniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GAL_zawieszkiOperationCompleted;
        
        private System.Threading.SendOrPostCallback Wyczysc_zlecenie_z_telewizoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback GAL_Powody_brakowOperationCompleted;
        
        private System.Threading.SendOrPostCallback Zaloz_transferM4OperationCompleted;
        
        private System.Threading.SendOrPostCallback Date2JTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Time2JTOperationCompleted;
        
        private System.Threading.SendOrPostCallback Wyczysc_zlecenia_na_telewizorzeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendToTCPListenerOperationCompleted;
        
        private System.Threading.SendOrPostCallback Aktualizuj_dniOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service2() {
            this.Url = global::IPO_JDE_conn.Properties.Settings.Default.IPO_JDE_conn_WebReference2_Service2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GAL_Pobierz_zdjeciaCompletedEventHandler GAL_Pobierz_zdjeciaCompleted;
        
        /// <remarks/>
        public event GAL_dane_zleceniaCompletedEventHandler GAL_dane_zleceniaCompleted;
        
        /// <remarks/>
        public event GAL_zawieszkiCompletedEventHandler GAL_zawieszkiCompleted;
        
        /// <remarks/>
        public event Wyczysc_zlecenie_z_telewizoraCompletedEventHandler Wyczysc_zlecenie_z_telewizoraCompleted;
        
        /// <remarks/>
        public event GAL_Powody_brakowCompletedEventHandler GAL_Powody_brakowCompleted;
        
        /// <remarks/>
        public event Zaloz_transferM4CompletedEventHandler Zaloz_transferM4Completed;
        
        /// <remarks/>
        public event Date2JTCompletedEventHandler Date2JTCompleted;
        
        /// <remarks/>
        public event Time2JTCompletedEventHandler Time2JTCompleted;
        
        /// <remarks/>
        public event Wyczysc_zlecenia_na_telewizorzeCompletedEventHandler Wyczysc_zlecenia_na_telewizorzeCompleted;
        
        /// <remarks/>
        public event SendToTCPListenerCompletedEventHandler SendToTCPListenerCompleted;
        
        /// <remarks/>
        public event Aktualizuj_dniCompletedEventHandler Aktualizuj_dniCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GAL_Pobierz_zdjecia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GAL_Pobierz_zdjecia(int id_zawieszki, int nr_zd) {
            object[] results = this.Invoke("GAL_Pobierz_zdjecia", new object[] {
                        id_zawieszki,
                        nr_zd});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GAL_Pobierz_zdjeciaAsync(int id_zawieszki, int nr_zd) {
            this.GAL_Pobierz_zdjeciaAsync(id_zawieszki, nr_zd, null);
        }
        
        /// <remarks/>
        public void GAL_Pobierz_zdjeciaAsync(int id_zawieszki, int nr_zd, object userState) {
            if ((this.GAL_Pobierz_zdjeciaOperationCompleted == null)) {
                this.GAL_Pobierz_zdjeciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGAL_Pobierz_zdjeciaOperationCompleted);
            }
            this.InvokeAsync("GAL_Pobierz_zdjecia", new object[] {
                        id_zawieszki,
                        nr_zd}, this.GAL_Pobierz_zdjeciaOperationCompleted, userState);
        }
        
        private void OnGAL_Pobierz_zdjeciaOperationCompleted(object arg) {
            if ((this.GAL_Pobierz_zdjeciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GAL_Pobierz_zdjeciaCompleted(this, new GAL_Pobierz_zdjeciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GAL_dane_zlecenia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IPO_ZLECENIA[] GAL_dane_zlecenia(int id_zlec) {
            object[] results = this.Invoke("GAL_dane_zlecenia", new object[] {
                        id_zlec});
            return ((IPO_ZLECENIA[])(results[0]));
        }
        
        /// <remarks/>
        public void GAL_dane_zleceniaAsync(int id_zlec) {
            this.GAL_dane_zleceniaAsync(id_zlec, null);
        }
        
        /// <remarks/>
        public void GAL_dane_zleceniaAsync(int id_zlec, object userState) {
            if ((this.GAL_dane_zleceniaOperationCompleted == null)) {
                this.GAL_dane_zleceniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGAL_dane_zleceniaOperationCompleted);
            }
            this.InvokeAsync("GAL_dane_zlecenia", new object[] {
                        id_zlec}, this.GAL_dane_zleceniaOperationCompleted, userState);
        }
        
        private void OnGAL_dane_zleceniaOperationCompleted(object arg) {
            if ((this.GAL_dane_zleceniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GAL_dane_zleceniaCompleted(this, new GAL_dane_zleceniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GAL_zawieszki", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GAL_ZAWIESZKI[] GAL_zawieszki(int item_id) {
            object[] results = this.Invoke("GAL_zawieszki", new object[] {
                        item_id});
            return ((GAL_ZAWIESZKI[])(results[0]));
        }
        
        /// <remarks/>
        public void GAL_zawieszkiAsync(int item_id) {
            this.GAL_zawieszkiAsync(item_id, null);
        }
        
        /// <remarks/>
        public void GAL_zawieszkiAsync(int item_id, object userState) {
            if ((this.GAL_zawieszkiOperationCompleted == null)) {
                this.GAL_zawieszkiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGAL_zawieszkiOperationCompleted);
            }
            this.InvokeAsync("GAL_zawieszki", new object[] {
                        item_id}, this.GAL_zawieszkiOperationCompleted, userState);
        }
        
        private void OnGAL_zawieszkiOperationCompleted(object arg) {
            if ((this.GAL_zawieszkiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GAL_zawieszkiCompleted(this, new GAL_zawieszkiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Wyczysc_zlecenie_z_telewizora", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Wyczysc_zlecenie_z_telewizora(int nr_zlecenia) {
            this.Invoke("Wyczysc_zlecenie_z_telewizora", new object[] {
                        nr_zlecenia});
        }
        
        /// <remarks/>
        public void Wyczysc_zlecenie_z_telewizoraAsync(int nr_zlecenia) {
            this.Wyczysc_zlecenie_z_telewizoraAsync(nr_zlecenia, null);
        }
        
        /// <remarks/>
        public void Wyczysc_zlecenie_z_telewizoraAsync(int nr_zlecenia, object userState) {
            if ((this.Wyczysc_zlecenie_z_telewizoraOperationCompleted == null)) {
                this.Wyczysc_zlecenie_z_telewizoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyczysc_zlecenie_z_telewizoraOperationCompleted);
            }
            this.InvokeAsync("Wyczysc_zlecenie_z_telewizora", new object[] {
                        nr_zlecenia}, this.Wyczysc_zlecenie_z_telewizoraOperationCompleted, userState);
        }
        
        private void OnWyczysc_zlecenie_z_telewizoraOperationCompleted(object arg) {
            if ((this.Wyczysc_zlecenie_z_telewizoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Wyczysc_zlecenie_z_telewizoraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GAL_Powody_brakow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GAL_Powody_brakow() {
            object[] results = this.Invoke("GAL_Powody_brakow", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GAL_Powody_brakowAsync() {
            this.GAL_Powody_brakowAsync(null);
        }
        
        /// <remarks/>
        public void GAL_Powody_brakowAsync(object userState) {
            if ((this.GAL_Powody_brakowOperationCompleted == null)) {
                this.GAL_Powody_brakowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGAL_Powody_brakowOperationCompleted);
            }
            this.InvokeAsync("GAL_Powody_brakow", new object[0], this.GAL_Powody_brakowOperationCompleted, userState);
        }
        
        private void OnGAL_Powody_brakowOperationCompleted(object arg) {
            if ((this.GAL_Powody_brakowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GAL_Powody_brakowCompleted(this, new GAL_Powody_brakowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Zaloz_transferM4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Zaloz_transferM4(string mag_z, string lok_z, string litm, string mag_do, int qty, string JM, string utworzyl, string komentarz) {
            object[] results = this.Invoke("Zaloz_transferM4", new object[] {
                        mag_z,
                        lok_z,
                        litm,
                        mag_do,
                        qty,
                        JM,
                        utworzyl,
                        komentarz});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Zaloz_transferM4Async(string mag_z, string lok_z, string litm, string mag_do, int qty, string JM, string utworzyl, string komentarz) {
            this.Zaloz_transferM4Async(mag_z, lok_z, litm, mag_do, qty, JM, utworzyl, komentarz, null);
        }
        
        /// <remarks/>
        public void Zaloz_transferM4Async(string mag_z, string lok_z, string litm, string mag_do, int qty, string JM, string utworzyl, string komentarz, object userState) {
            if ((this.Zaloz_transferM4OperationCompleted == null)) {
                this.Zaloz_transferM4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZaloz_transferM4OperationCompleted);
            }
            this.InvokeAsync("Zaloz_transferM4", new object[] {
                        mag_z,
                        lok_z,
                        litm,
                        mag_do,
                        qty,
                        JM,
                        utworzyl,
                        komentarz}, this.Zaloz_transferM4OperationCompleted, userState);
        }
        
        private void OnZaloz_transferM4OperationCompleted(object arg) {
            if ((this.Zaloz_transferM4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zaloz_transferM4Completed(this, new Zaloz_transferM4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Date2JT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Date2JT(System.DateTime dt) {
            object[] results = this.Invoke("Date2JT", new object[] {
                        dt});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Date2JTAsync(System.DateTime dt) {
            this.Date2JTAsync(dt, null);
        }
        
        /// <remarks/>
        public void Date2JTAsync(System.DateTime dt, object userState) {
            if ((this.Date2JTOperationCompleted == null)) {
                this.Date2JTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDate2JTOperationCompleted);
            }
            this.InvokeAsync("Date2JT", new object[] {
                        dt}, this.Date2JTOperationCompleted, userState);
        }
        
        private void OnDate2JTOperationCompleted(object arg) {
            if ((this.Date2JTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Date2JTCompleted(this, new Date2JTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Time2JT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Time2JT(System.DateTime dt) {
            object[] results = this.Invoke("Time2JT", new object[] {
                        dt});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Time2JTAsync(System.DateTime dt) {
            this.Time2JTAsync(dt, null);
        }
        
        /// <remarks/>
        public void Time2JTAsync(System.DateTime dt, object userState) {
            if ((this.Time2JTOperationCompleted == null)) {
                this.Time2JTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTime2JTOperationCompleted);
            }
            this.InvokeAsync("Time2JT", new object[] {
                        dt}, this.Time2JTOperationCompleted, userState);
        }
        
        private void OnTime2JTOperationCompleted(object arg) {
            if ((this.Time2JTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Time2JTCompleted(this, new Time2JTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Wyczysc_zlecenia_na_telewizorze", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Wyczysc_zlecenia_na_telewizorze() {
            this.Invoke("Wyczysc_zlecenia_na_telewizorze", new object[0]);
        }
        
        /// <remarks/>
        public void Wyczysc_zlecenia_na_telewizorzeAsync() {
            this.Wyczysc_zlecenia_na_telewizorzeAsync(null);
        }
        
        /// <remarks/>
        public void Wyczysc_zlecenia_na_telewizorzeAsync(object userState) {
            if ((this.Wyczysc_zlecenia_na_telewizorzeOperationCompleted == null)) {
                this.Wyczysc_zlecenia_na_telewizorzeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWyczysc_zlecenia_na_telewizorzeOperationCompleted);
            }
            this.InvokeAsync("Wyczysc_zlecenia_na_telewizorze", new object[0], this.Wyczysc_zlecenia_na_telewizorzeOperationCompleted, userState);
        }
        
        private void OnWyczysc_zlecenia_na_telewizorzeOperationCompleted(object arg) {
            if ((this.Wyczysc_zlecenia_na_telewizorzeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Wyczysc_zlecenia_na_telewizorzeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendToTCPListener", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendToTCPListener(string Server, int port, string message) {
            object[] results = this.Invoke("SendToTCPListener", new object[] {
                        Server,
                        port,
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendToTCPListenerAsync(string Server, int port, string message) {
            this.SendToTCPListenerAsync(Server, port, message, null);
        }
        
        /// <remarks/>
        public void SendToTCPListenerAsync(string Server, int port, string message, object userState) {
            if ((this.SendToTCPListenerOperationCompleted == null)) {
                this.SendToTCPListenerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendToTCPListenerOperationCompleted);
            }
            this.InvokeAsync("SendToTCPListener", new object[] {
                        Server,
                        port,
                        message}, this.SendToTCPListenerOperationCompleted, userState);
        }
        
        private void OnSendToTCPListenerOperationCompleted(object arg) {
            if ((this.SendToTCPListenerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendToTCPListenerCompleted(this, new SendToTCPListenerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Aktualizuj_dni", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Aktualizuj_dni() {
            object[] results = this.Invoke("Aktualizuj_dni", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Aktualizuj_dniAsync() {
            this.Aktualizuj_dniAsync(null);
        }
        
        /// <remarks/>
        public void Aktualizuj_dniAsync(object userState) {
            if ((this.Aktualizuj_dniOperationCompleted == null)) {
                this.Aktualizuj_dniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAktualizuj_dniOperationCompleted);
            }
            this.InvokeAsync("Aktualizuj_dni", new object[0], this.Aktualizuj_dniOperationCompleted, userState);
        }
        
        private void OnAktualizuj_dniOperationCompleted(object arg) {
            if ((this.Aktualizuj_dniCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Aktualizuj_dniCompleted(this, new Aktualizuj_dniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IPO_ZLECENIA {
        
        private int ipo_idField;
        
        private string indeks_zleceniaField;
        
        private string contractor_idField;
        
        private int zlec_wewField;
        
        private string nr_rysunkuField;
        
        private int expr1Field;
        
        private int expr2Field;
        
        private int idField;
        
        private int ipo_nr_zlecField;
        
        private string nr_ITMField;
        
        private string nr_zam_klientaField;
        
        private System.Nullable<System.DateTime> start_zamField;
        
        private System.Nullable<System.DateTime> stop_zamField;
        
        private int ilosc_zamField;
        
        private int ilosc_wyprField;
        
        private int ilosc_brakField;
        
        private string nr_seriiField;
        
        private string magazyn_wejField;
        
        private string status_zamField;
        
        private System.DateTime dataUtworzeniaField;
        
        private int priorytetField;
        
        private System.Nullable<double> wspField;
        
        private string kOLORField;
        
        private string kOD_PLANField;
        
        private System.Nullable<int> hala_idField;
        
        private string cecha_AField;
        
        private string cecha_BField;
        
        private string cecha_PField;
        
        private string cecha_QField;
        
        private string nAZWAField;
        
        /// <remarks/>
        public int ipo_id {
            get {
                return this.ipo_idField;
            }
            set {
                this.ipo_idField = value;
            }
        }
        
        /// <remarks/>
        public string Indeks_zlecenia {
            get {
                return this.indeks_zleceniaField;
            }
            set {
                this.indeks_zleceniaField = value;
            }
        }
        
        /// <remarks/>
        public string contractor_id {
            get {
                return this.contractor_idField;
            }
            set {
                this.contractor_idField = value;
            }
        }
        
        /// <remarks/>
        public int zlec_wew {
            get {
                return this.zlec_wewField;
            }
            set {
                this.zlec_wewField = value;
            }
        }
        
        /// <remarks/>
        public string nr_rysunku {
            get {
                return this.nr_rysunkuField;
            }
            set {
                this.nr_rysunkuField = value;
            }
        }
        
        /// <remarks/>
        public int Expr1 {
            get {
                return this.expr1Field;
            }
            set {
                this.expr1Field = value;
            }
        }
        
        /// <remarks/>
        public int Expr2 {
            get {
                return this.expr2Field;
            }
            set {
                this.expr2Field = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int ipo_nr_zlec {
            get {
                return this.ipo_nr_zlecField;
            }
            set {
                this.ipo_nr_zlecField = value;
            }
        }
        
        /// <remarks/>
        public string nr_ITM {
            get {
                return this.nr_ITMField;
            }
            set {
                this.nr_ITMField = value;
            }
        }
        
        /// <remarks/>
        public string nr_zam_klienta {
            get {
                return this.nr_zam_klientaField;
            }
            set {
                this.nr_zam_klientaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> start_zam {
            get {
                return this.start_zamField;
            }
            set {
                this.start_zamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> stop_zam {
            get {
                return this.stop_zamField;
            }
            set {
                this.stop_zamField = value;
            }
        }
        
        /// <remarks/>
        public int ilosc_zam {
            get {
                return this.ilosc_zamField;
            }
            set {
                this.ilosc_zamField = value;
            }
        }
        
        /// <remarks/>
        public int ilosc_wypr {
            get {
                return this.ilosc_wyprField;
            }
            set {
                this.ilosc_wyprField = value;
            }
        }
        
        /// <remarks/>
        public int ilosc_brak {
            get {
                return this.ilosc_brakField;
            }
            set {
                this.ilosc_brakField = value;
            }
        }
        
        /// <remarks/>
        public string nr_serii {
            get {
                return this.nr_seriiField;
            }
            set {
                this.nr_seriiField = value;
            }
        }
        
        /// <remarks/>
        public string magazyn_wej {
            get {
                return this.magazyn_wejField;
            }
            set {
                this.magazyn_wejField = value;
            }
        }
        
        /// <remarks/>
        public string Status_zam {
            get {
                return this.status_zamField;
            }
            set {
                this.status_zamField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dataUtworzenia {
            get {
                return this.dataUtworzeniaField;
            }
            set {
                this.dataUtworzeniaField = value;
            }
        }
        
        /// <remarks/>
        public int priorytet {
            get {
                return this.priorytetField;
            }
            set {
                this.priorytetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> wsp {
            get {
                return this.wspField;
            }
            set {
                this.wspField = value;
            }
        }
        
        /// <remarks/>
        public string KOLOR {
            get {
                return this.kOLORField;
            }
            set {
                this.kOLORField = value;
            }
        }
        
        /// <remarks/>
        public string KOD_PLAN {
            get {
                return this.kOD_PLANField;
            }
            set {
                this.kOD_PLANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> hala_id {
            get {
                return this.hala_idField;
            }
            set {
                this.hala_idField = value;
            }
        }
        
        /// <remarks/>
        public string cecha_A {
            get {
                return this.cecha_AField;
            }
            set {
                this.cecha_AField = value;
            }
        }
        
        /// <remarks/>
        public string cecha_B {
            get {
                return this.cecha_BField;
            }
            set {
                this.cecha_BField = value;
            }
        }
        
        /// <remarks/>
        public string cecha_P {
            get {
                return this.cecha_PField;
            }
            set {
                this.cecha_PField = value;
            }
        }
        
        /// <remarks/>
        public string cecha_Q {
            get {
                return this.cecha_QField;
            }
            set {
                this.cecha_QField = value;
            }
        }
        
        /// <remarks/>
        public string NAZWA {
            get {
                return this.nAZWAField;
            }
            set {
                this.nAZWAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GAL_ZAWIESZKI {
        
        private int idField;
        
        private string nr_rysunkuField;
        
        private string nr_zawieszkiField;
        
        private string programField;
        
        private System.Nullable<int> il_sztField;
        
        private string komentarzField;
        
        private System.Nullable<System.DateTime> createdField;
        
        private string createdByField;
        
        private System.Nullable<int> ilosc_zdjęćField;
        
        private string gALMALField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nr_rysunku {
            get {
                return this.nr_rysunkuField;
            }
            set {
                this.nr_rysunkuField = value;
            }
        }
        
        /// <remarks/>
        public string Nr_zawieszki {
            get {
                return this.nr_zawieszkiField;
            }
            set {
                this.nr_zawieszkiField = value;
            }
        }
        
        /// <remarks/>
        public string Program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Il_szt {
            get {
                return this.il_sztField;
            }
            set {
                this.il_sztField = value;
            }
        }
        
        /// <remarks/>
        public string Komentarz {
            get {
                return this.komentarzField;
            }
            set {
                this.komentarzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Ilosc_zdjęć {
            get {
                return this.ilosc_zdjęćField;
            }
            set {
                this.ilosc_zdjęćField = value;
            }
        }
        
        /// <remarks/>
        public string GALMAL {
            get {
                return this.gALMALField;
            }
            set {
                this.gALMALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GAL_Pobierz_zdjeciaCompletedEventHandler(object sender, GAL_Pobierz_zdjeciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GAL_Pobierz_zdjeciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GAL_Pobierz_zdjeciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GAL_dane_zleceniaCompletedEventHandler(object sender, GAL_dane_zleceniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GAL_dane_zleceniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GAL_dane_zleceniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IPO_ZLECENIA[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IPO_ZLECENIA[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GAL_zawieszkiCompletedEventHandler(object sender, GAL_zawieszkiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GAL_zawieszkiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GAL_zawieszkiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GAL_ZAWIESZKI[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GAL_ZAWIESZKI[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Wyczysc_zlecenie_z_telewizoraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GAL_Powody_brakowCompletedEventHandler(object sender, GAL_Powody_brakowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GAL_Powody_brakowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GAL_Powody_brakowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Zaloz_transferM4CompletedEventHandler(object sender, Zaloz_transferM4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Zaloz_transferM4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Zaloz_transferM4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Date2JTCompletedEventHandler(object sender, Date2JTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Date2JTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Date2JTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Time2JTCompletedEventHandler(object sender, Time2JTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Time2JTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Time2JTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Wyczysc_zlecenia_na_telewizorzeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendToTCPListenerCompletedEventHandler(object sender, SendToTCPListenerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendToTCPListenerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendToTCPListenerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Aktualizuj_dniCompletedEventHandler(object sender, Aktualizuj_dniCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Aktualizuj_dniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Aktualizuj_dniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591