#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPO_JDE_conn
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="trans")]
	public partial class dbtransDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertH7_REKLASYFIKACJA(H7_REKLASYFIKACJA instance);
    partial void UpdateH7_REKLASYFIKACJA(H7_REKLASYFIKACJA instance);
    partial void DeleteH7_REKLASYFIKACJA(H7_REKLASYFIKACJA instance);
    partial void InsertPALETY62(PALETY62 instance);
    partial void UpdatePALETY62(PALETY62 instance);
    partial void DeletePALETY62(PALETY62 instance);
    #endregion
		
		public dbtransDataContext() : 
				base(global::IPO_JDE_conn.Properties.Settings.Default.transConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbtransDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<H7_REKLASYFIKACJA> H7_REKLASYFIKACJAs
		{
			get
			{
				return this.GetTable<H7_REKLASYFIKACJA>();
			}
		}
		
		public System.Data.Linq.Table<PALETY62> PALETY62s
		{
			get
			{
				return this.GetTable<PALETY62>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.H7_REKLASYFIKACJA")]
	public partial class H7_REKLASYFIKACJA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _indeks_z;
		
		private string _indeks_do;
		
		private System.Nullable<int> _ilosc;
		
		private string _magazyn_z;
		
		private string _lokalizacja_z;
		
		private string _wynik;
		
		private string _User;
		
		private System.Nullable<System.DateTime> _Data_utw;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onindeks_zChanging(string value);
    partial void Onindeks_zChanged();
    partial void Onindeks_doChanging(string value);
    partial void Onindeks_doChanged();
    partial void OniloscChanging(System.Nullable<int> value);
    partial void OniloscChanged();
    partial void Onmagazyn_zChanging(string value);
    partial void Onmagazyn_zChanged();
    partial void Onlokalizacja_zChanging(string value);
    partial void Onlokalizacja_zChanged();
    partial void OnwynikChanging(string value);
    partial void OnwynikChanged();
    partial void OnUserChanging(string value);
    partial void OnUserChanged();
    partial void OnData_utwChanging(System.Nullable<System.DateTime> value);
    partial void OnData_utwChanged();
    #endregion
		
		public H7_REKLASYFIKACJA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indeks_z", DbType="NVarChar(50)")]
		public string indeks_z
		{
			get
			{
				return this._indeks_z;
			}
			set
			{
				if ((this._indeks_z != value))
				{
					this.Onindeks_zChanging(value);
					this.SendPropertyChanging();
					this._indeks_z = value;
					this.SendPropertyChanged("indeks_z");
					this.Onindeks_zChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indeks_do", DbType="NVarChar(50)")]
		public string indeks_do
		{
			get
			{
				return this._indeks_do;
			}
			set
			{
				if ((this._indeks_do != value))
				{
					this.Onindeks_doChanging(value);
					this.SendPropertyChanging();
					this._indeks_do = value;
					this.SendPropertyChanged("indeks_do");
					this.Onindeks_doChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilosc", DbType="Int")]
		public System.Nullable<int> ilosc
		{
			get
			{
				return this._ilosc;
			}
			set
			{
				if ((this._ilosc != value))
				{
					this.OniloscChanging(value);
					this.SendPropertyChanging();
					this._ilosc = value;
					this.SendPropertyChanged("ilosc");
					this.OniloscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magazyn_z", DbType="NVarChar(50)")]
		public string magazyn_z
		{
			get
			{
				return this._magazyn_z;
			}
			set
			{
				if ((this._magazyn_z != value))
				{
					this.Onmagazyn_zChanging(value);
					this.SendPropertyChanging();
					this._magazyn_z = value;
					this.SendPropertyChanged("magazyn_z");
					this.Onmagazyn_zChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lokalizacja_z", DbType="NVarChar(50)")]
		public string lokalizacja_z
		{
			get
			{
				return this._lokalizacja_z;
			}
			set
			{
				if ((this._lokalizacja_z != value))
				{
					this.Onlokalizacja_zChanging(value);
					this.SendPropertyChanging();
					this._lokalizacja_z = value;
					this.SendPropertyChanged("lokalizacja_z");
					this.Onlokalizacja_zChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wynik", DbType="NVarChar(50)")]
		public string wynik
		{
			get
			{
				return this._wynik;
			}
			set
			{
				if ((this._wynik != value))
				{
					this.OnwynikChanging(value);
					this.SendPropertyChanging();
					this._wynik = value;
					this.SendPropertyChanged("wynik");
					this.OnwynikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_utw", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Data_utw
		{
			get
			{
				return this._Data_utw;
			}
			set
			{
				if ((this._Data_utw != value))
				{
					this.OnData_utwChanging(value);
					this.SendPropertyChanging();
					this._Data_utw = value;
					this.SendPropertyChanged("Data_utw");
					this.OnData_utwChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PALETY62")]
	public partial class PALETY62 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nr_palety;
		
		private string _lok;
		
		private string _UserName;
		
		private System.Nullable<System.DateTime> _Data_utw;
		
		private bool _ANULOWANY;
		
		private string _Indeks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNr_paletyChanging(string value);
    partial void OnNr_paletyChanged();
    partial void OnlokChanging(string value);
    partial void OnlokChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnData_utwChanging(System.Nullable<System.DateTime> value);
    partial void OnData_utwChanged();
    partial void OnANULOWANYChanging(bool value);
    partial void OnANULOWANYChanged();
    partial void OnIndeksChanging(string value);
    partial void OnIndeksChanged();
    #endregion
		
		public PALETY62()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nr_palety", DbType="NVarChar(50)")]
		public string Nr_palety
		{
			get
			{
				return this._Nr_palety;
			}
			set
			{
				if ((this._Nr_palety != value))
				{
					this.OnNr_paletyChanging(value);
					this.SendPropertyChanging();
					this._Nr_palety = value;
					this.SendPropertyChanged("Nr_palety");
					this.OnNr_paletyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lok", DbType="NVarChar(50)")]
		public string lok
		{
			get
			{
				return this._lok;
			}
			set
			{
				if ((this._lok != value))
				{
					this.OnlokChanging(value);
					this.SendPropertyChanging();
					this._lok = value;
					this.SendPropertyChanged("lok");
					this.OnlokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_utw", DbType="DateTime2")]
		public System.Nullable<System.DateTime> Data_utw
		{
			get
			{
				return this._Data_utw;
			}
			set
			{
				if ((this._Data_utw != value))
				{
					this.OnData_utwChanging(value);
					this.SendPropertyChanging();
					this._Data_utw = value;
					this.SendPropertyChanged("Data_utw");
					this.OnData_utwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANULOWANY", DbType="Bit NOT NULL")]
		public bool ANULOWANY
		{
			get
			{
				return this._ANULOWANY;
			}
			set
			{
				if ((this._ANULOWANY != value))
				{
					this.OnANULOWANYChanging(value);
					this.SendPropertyChanging();
					this._ANULOWANY = value;
					this.SendPropertyChanged("ANULOWANY");
					this.OnANULOWANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indeks", DbType="NVarChar(50)")]
		public string Indeks
		{
			get
			{
				return this._Indeks;
			}
			set
			{
				if ((this._Indeks != value))
				{
					this.OnIndeksChanging(value);
					this.SendPropertyChanging();
					this._Indeks = value;
					this.SendPropertyChanged("Indeks");
					this.OnIndeksChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
