//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IPO_JDE_conn.WEB_IPO {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IPOSoap", Namespace="http://tempuri.org/")]
    public partial class IPO : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZrobBoostaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Odrzuc_zlecenieOperationCompleted;
        
        private System.Threading.SendOrPostCallback Usuń_zamiennikOperationCompleted;
        
        private System.Threading.SendOrPostCallback Zmien_blokade_indeksuOperationCompleted;
        
        private System.Threading.SendOrPostCallback Dodaj_zamiennik_idOperationCompleted;
        
        private System.Threading.SendOrPostCallback Dodaj_zamiennikOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IPO() {
            this.Url = global::IPO_JDE_conn.Properties.Settings.Default.IPO_JDE_conn_WEB_IPO_IPO;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZrobBoostaCompletedEventHandler ZrobBoostaCompleted;
        
        /// <remarks/>
        public event Odrzuc_zlecenieCompletedEventHandler Odrzuc_zlecenieCompleted;
        
        /// <remarks/>
        public event Usuń_zamiennikCompletedEventHandler Usuń_zamiennikCompleted;
        
        /// <remarks/>
        public event Zmien_blokade_indeksuCompletedEventHandler Zmien_blokade_indeksuCompleted;
        
        /// <remarks/>
        public event Dodaj_zamiennik_idCompletedEventHandler Dodaj_zamiennik_idCompleted;
        
        /// <remarks/>
        public event Dodaj_zamiennikCompletedEventHandler Dodaj_zamiennikCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ZrobBoosta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ZrobBoosta(int Nr_zlec_ipo) {
            object[] results = this.Invoke("ZrobBoosta", new object[] {
                        Nr_zlec_ipo});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ZrobBoostaAsync(int Nr_zlec_ipo) {
            this.ZrobBoostaAsync(Nr_zlec_ipo, null);
        }
        
        /// <remarks/>
        public void ZrobBoostaAsync(int Nr_zlec_ipo, object userState) {
            if ((this.ZrobBoostaOperationCompleted == null)) {
                this.ZrobBoostaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZrobBoostaOperationCompleted);
            }
            this.InvokeAsync("ZrobBoosta", new object[] {
                        Nr_zlec_ipo}, this.ZrobBoostaOperationCompleted, userState);
        }
        
        private void OnZrobBoostaOperationCompleted(object arg) {
            if ((this.ZrobBoostaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZrobBoostaCompleted(this, new ZrobBoostaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Odrzuc_zlecenie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Odrzuc_zlecenie(int id_zlec, string id_usera) {
            object[] results = this.Invoke("Odrzuc_zlecenie", new object[] {
                        id_zlec,
                        id_usera});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Odrzuc_zlecenieAsync(int id_zlec, string id_usera) {
            this.Odrzuc_zlecenieAsync(id_zlec, id_usera, null);
        }
        
        /// <remarks/>
        public void Odrzuc_zlecenieAsync(int id_zlec, string id_usera, object userState) {
            if ((this.Odrzuc_zlecenieOperationCompleted == null)) {
                this.Odrzuc_zlecenieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOdrzuc_zlecenieOperationCompleted);
            }
            this.InvokeAsync("Odrzuc_zlecenie", new object[] {
                        id_zlec,
                        id_usera}, this.Odrzuc_zlecenieOperationCompleted, userState);
        }
        
        private void OnOdrzuc_zlecenieOperationCompleted(object arg) {
            if ((this.Odrzuc_zlecenieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Odrzuc_zlecenieCompleted(this, new Odrzuc_zlecenieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Usuń_zamiennik", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Usuń_zamiennik(int id_klucz) {
            object[] results = this.Invoke("Usuń_zamiennik", new object[] {
                        id_klucz});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Usuń_zamiennikAsync(int id_klucz) {
            this.Usuń_zamiennikAsync(id_klucz, null);
        }
        
        /// <remarks/>
        public void Usuń_zamiennikAsync(int id_klucz, object userState) {
            if ((this.Usuń_zamiennikOperationCompleted == null)) {
                this.Usuń_zamiennikOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuń_zamiennikOperationCompleted);
            }
            this.InvokeAsync("Usuń_zamiennik", new object[] {
                        id_klucz}, this.Usuń_zamiennikOperationCompleted, userState);
        }
        
        private void OnUsuń_zamiennikOperationCompleted(object arg) {
            if ((this.Usuń_zamiennikCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Usuń_zamiennikCompleted(this, new Usuń_zamiennikCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Zmien_blokade_indeksu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Zmien_blokade_indeksu(string indeks, bool blokada) {
            this.Invoke("Zmien_blokade_indeksu", new object[] {
                        indeks,
                        blokada});
        }
        
        /// <remarks/>
        public void Zmien_blokade_indeksuAsync(string indeks, bool blokada) {
            this.Zmien_blokade_indeksuAsync(indeks, blokada, null);
        }
        
        /// <remarks/>
        public void Zmien_blokade_indeksuAsync(string indeks, bool blokada, object userState) {
            if ((this.Zmien_blokade_indeksuOperationCompleted == null)) {
                this.Zmien_blokade_indeksuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZmien_blokade_indeksuOperationCompleted);
            }
            this.InvokeAsync("Zmien_blokade_indeksu", new object[] {
                        indeks,
                        blokada}, this.Zmien_blokade_indeksuOperationCompleted, userState);
        }
        
        private void OnZmien_blokade_indeksuOperationCompleted(object arg) {
            if ((this.Zmien_blokade_indeksuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Zmien_blokade_indeksuCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Dodaj_zamiennik_id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Dodaj_zamiennik_id(int id_potrzeby, string litm_zamiennik, double ilosc) {
            object[] results = this.Invoke("Dodaj_zamiennik_id", new object[] {
                        id_potrzeby,
                        litm_zamiennik,
                        ilosc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Dodaj_zamiennik_idAsync(int id_potrzeby, string litm_zamiennik, double ilosc) {
            this.Dodaj_zamiennik_idAsync(id_potrzeby, litm_zamiennik, ilosc, null);
        }
        
        /// <remarks/>
        public void Dodaj_zamiennik_idAsync(int id_potrzeby, string litm_zamiennik, double ilosc, object userState) {
            if ((this.Dodaj_zamiennik_idOperationCompleted == null)) {
                this.Dodaj_zamiennik_idOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDodaj_zamiennik_idOperationCompleted);
            }
            this.InvokeAsync("Dodaj_zamiennik_id", new object[] {
                        id_potrzeby,
                        litm_zamiennik,
                        ilosc}, this.Dodaj_zamiennik_idOperationCompleted, userState);
        }
        
        private void OnDodaj_zamiennik_idOperationCompleted(object arg) {
            if ((this.Dodaj_zamiennik_idCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Dodaj_zamiennik_idCompleted(this, new Dodaj_zamiennik_idCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Dodaj_zamiennik", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Dodaj_zamiennik(int nr_szablonu, string litm_materialu, string litm_zamiennik, double ilosc) {
            object[] results = this.Invoke("Dodaj_zamiennik", new object[] {
                        nr_szablonu,
                        litm_materialu,
                        litm_zamiennik,
                        ilosc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Dodaj_zamiennikAsync(int nr_szablonu, string litm_materialu, string litm_zamiennik, double ilosc) {
            this.Dodaj_zamiennikAsync(nr_szablonu, litm_materialu, litm_zamiennik, ilosc, null);
        }
        
        /// <remarks/>
        public void Dodaj_zamiennikAsync(int nr_szablonu, string litm_materialu, string litm_zamiennik, double ilosc, object userState) {
            if ((this.Dodaj_zamiennikOperationCompleted == null)) {
                this.Dodaj_zamiennikOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDodaj_zamiennikOperationCompleted);
            }
            this.InvokeAsync("Dodaj_zamiennik", new object[] {
                        nr_szablonu,
                        litm_materialu,
                        litm_zamiennik,
                        ilosc}, this.Dodaj_zamiennikOperationCompleted, userState);
        }
        
        private void OnDodaj_zamiennikOperationCompleted(object arg) {
            if ((this.Dodaj_zamiennikCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Dodaj_zamiennikCompleted(this, new Dodaj_zamiennikCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZrobBoostaCompletedEventHandler(object sender, ZrobBoostaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZrobBoostaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZrobBoostaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Odrzuc_zlecenieCompletedEventHandler(object sender, Odrzuc_zlecenieCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Odrzuc_zlecenieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Odrzuc_zlecenieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Usuń_zamiennikCompletedEventHandler(object sender, Usuń_zamiennikCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Usuń_zamiennikCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Usuń_zamiennikCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Zmien_blokade_indeksuCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Dodaj_zamiennik_idCompletedEventHandler(object sender, Dodaj_zamiennik_idCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dodaj_zamiennik_idCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Dodaj_zamiennik_idCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Dodaj_zamiennikCompletedEventHandler(object sender, Dodaj_zamiennikCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dodaj_zamiennikCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Dodaj_zamiennikCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591