//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IPO_JDE_conn.IPO_PRACE_ZEWN {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Prace_zewn_APISoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(external_tasks_list[]))]
    public partial class Prace_zewn_API : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTasksToDoOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndTaskOperationCompleted;
        
        private System.Threading.SendOrPostCallback Report_taskOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Prace_zewn_API() {
            this.Url = global::IPO_JDE_conn.Properties.Settings.Default.IPO_JDE_conn_IPO_PRACE_ZEWN_Prace_zewn_API;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTasksToDoCompletedEventHandler GetTasksToDoCompleted;
        
        /// <remarks/>
        public event StartTaskCompletedEventHandler StartTaskCompleted;
        
        /// <remarks/>
        public event EndTaskCompletedEventHandler EndTaskCompleted;
        
        /// <remarks/>
        public event Report_taskCompletedEventHandler Report_taskCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTasksToDo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public external_tasks_list[] GetTasksToDo(string okod) {
            object[] results = this.Invoke("GetTasksToDo", new object[] {
                        okod});
            return ((external_tasks_list[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTasksToDoAsync(string okod) {
            this.GetTasksToDoAsync(okod, null);
        }
        
        /// <remarks/>
        public void GetTasksToDoAsync(string okod, object userState) {
            if ((this.GetTasksToDoOperationCompleted == null)) {
                this.GetTasksToDoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTasksToDoOperationCompleted);
            }
            this.InvokeAsync("GetTasksToDo", new object[] {
                        okod}, this.GetTasksToDoOperationCompleted, userState);
        }
        
        private void OnGetTasksToDoOperationCompleted(object arg) {
            if ((this.GetTasksToDoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTasksToDoCompleted(this, new GetTasksToDoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StartTask(int task_id, System.DateTime stop_time) {
            object[] results = this.Invoke("StartTask", new object[] {
                        task_id,
                        stop_time});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartTaskAsync(int task_id, System.DateTime stop_time) {
            this.StartTaskAsync(task_id, stop_time, null);
        }
        
        /// <remarks/>
        public void StartTaskAsync(int task_id, System.DateTime stop_time, object userState) {
            if ((this.StartTaskOperationCompleted == null)) {
                this.StartTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartTaskOperationCompleted);
            }
            this.InvokeAsync("StartTask", new object[] {
                        task_id,
                        stop_time}, this.StartTaskOperationCompleted, userState);
        }
        
        private void OnStartTaskOperationCompleted(object arg) {
            if ((this.StartTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartTaskCompleted(this, new StartTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndTask", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EndTask(int task_id) {
            object[] results = this.Invoke("EndTask", new object[] {
                        task_id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EndTaskAsync(int task_id) {
            this.EndTaskAsync(task_id, null);
        }
        
        /// <remarks/>
        public void EndTaskAsync(int task_id, object userState) {
            if ((this.EndTaskOperationCompleted == null)) {
                this.EndTaskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndTaskOperationCompleted);
            }
            this.InvokeAsync("EndTask", new object[] {
                        task_id}, this.EndTaskOperationCompleted, userState);
        }
        
        private void OnEndTaskOperationCompleted(object arg) {
            if ((this.EndTaskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndTaskCompleted(this, new EndTaskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Report_task", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Report_task(int task_id, int qty) {
            object[] results = this.Invoke("Report_task", new object[] {
                        task_id,
                        qty});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Report_taskAsync(int task_id, int qty) {
            this.Report_taskAsync(task_id, qty, null);
        }
        
        /// <remarks/>
        public void Report_taskAsync(int task_id, int qty, object userState) {
            if ((this.Report_taskOperationCompleted == null)) {
                this.Report_taskOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReport_taskOperationCompleted);
            }
            this.InvokeAsync("Report_task", new object[] {
                        task_id,
                        qty}, this.Report_taskOperationCompleted, userState);
        }
        
        private void OnReport_taskOperationCompleted(object arg) {
            if ((this.Report_taskCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Report_taskCompleted(this, new Report_taskCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class external_tasks_list {
        
        private string contractor_order_noField;
        
        private object device_idField;
        
        private string drawing_noField;
        
        private System.DateTime execution_dateField;
        
        private string feature_aField;
        
        private string feature_bField;
        
        private object feature_gField;
        
        private object feature_hField;
        
        private string feature_pField;
        
        private string feature_qField;
        
        private int ipo_order_idField;
        
        private object[] materialsField;
        
        private string operation_codeField;
        
        private string order_nameField;
        
        private string order_no_custField;
        
        private object[] paramssField;
        
        private bool params_enabledField;
        
        private string part_noField;
        
        private int priorityField;
        
        private int quantityField;
        
        private object storage_placeField;
        
        private int task_idField;
        
        private int task_stateField;
        
        /// <remarks/>
        public string contractor_order_no {
            get {
                return this.contractor_order_noField;
            }
            set {
                this.contractor_order_noField = value;
            }
        }
        
        /// <remarks/>
        public object device_id {
            get {
                return this.device_idField;
            }
            set {
                this.device_idField = value;
            }
        }
        
        /// <remarks/>
        public string drawing_no {
            get {
                return this.drawing_noField;
            }
            set {
                this.drawing_noField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime execution_date {
            get {
                return this.execution_dateField;
            }
            set {
                this.execution_dateField = value;
            }
        }
        
        /// <remarks/>
        public string feature_a {
            get {
                return this.feature_aField;
            }
            set {
                this.feature_aField = value;
            }
        }
        
        /// <remarks/>
        public string feature_b {
            get {
                return this.feature_bField;
            }
            set {
                this.feature_bField = value;
            }
        }
        
        /// <remarks/>
        public object feature_g {
            get {
                return this.feature_gField;
            }
            set {
                this.feature_gField = value;
            }
        }
        
        /// <remarks/>
        public object feature_h {
            get {
                return this.feature_hField;
            }
            set {
                this.feature_hField = value;
            }
        }
        
        /// <remarks/>
        public string feature_p {
            get {
                return this.feature_pField;
            }
            set {
                this.feature_pField = value;
            }
        }
        
        /// <remarks/>
        public string feature_q {
            get {
                return this.feature_qField;
            }
            set {
                this.feature_qField = value;
            }
        }
        
        /// <remarks/>
        public int ipo_order_id {
            get {
                return this.ipo_order_idField;
            }
            set {
                this.ipo_order_idField = value;
            }
        }
        
        /// <remarks/>
        public object[] materials {
            get {
                return this.materialsField;
            }
            set {
                this.materialsField = value;
            }
        }
        
        /// <remarks/>
        public string operation_code {
            get {
                return this.operation_codeField;
            }
            set {
                this.operation_codeField = value;
            }
        }
        
        /// <remarks/>
        public string order_name {
            get {
                return this.order_nameField;
            }
            set {
                this.order_nameField = value;
            }
        }
        
        /// <remarks/>
        public string order_no_cust {
            get {
                return this.order_no_custField;
            }
            set {
                this.order_no_custField = value;
            }
        }
        
        /// <remarks/>
        public object[] paramss {
            get {
                return this.paramssField;
            }
            set {
                this.paramssField = value;
            }
        }
        
        /// <remarks/>
        public bool params_enabled {
            get {
                return this.params_enabledField;
            }
            set {
                this.params_enabledField = value;
            }
        }
        
        /// <remarks/>
        public string part_no {
            get {
                return this.part_noField;
            }
            set {
                this.part_noField = value;
            }
        }
        
        /// <remarks/>
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public object storage_place {
            get {
                return this.storage_placeField;
            }
            set {
                this.storage_placeField = value;
            }
        }
        
        /// <remarks/>
        public int task_id {
            get {
                return this.task_idField;
            }
            set {
                this.task_idField = value;
            }
        }
        
        /// <remarks/>
        public int task_state {
            get {
                return this.task_stateField;
            }
            set {
                this.task_stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetTasksToDoCompletedEventHandler(object sender, GetTasksToDoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTasksToDoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTasksToDoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public external_tasks_list[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((external_tasks_list[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void StartTaskCompletedEventHandler(object sender, StartTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EndTaskCompletedEventHandler(object sender, EndTaskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Report_taskCompletedEventHandler(object sender, Report_taskCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Report_taskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Report_taskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591